version: '3.8'

services:
  nostr-home:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - PORT=3000
      - NOSTR_NPUB=${NOSTR_NPUB}
      - SITE_NAME=${SITE_NAME:-Nostr Home}
      - SITE_SUBTITLE=${SITE_SUBTITLE:-Your Decentralized Content}
    restart: unless-stopped
    networks:
      - nostr-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - nostr-home
    restart: unless-stopped
    networks:
      - nostr-network

networks:
  nostr-network:
    driver: bridge
